[tool.poetry]
name = "fable-library"
version = "0.9.0"
description = "Fable library for Python"
authors = ["Dag Brattli <dag@brattli.net>"]
license = "MIT License"
readme = "README.md"
homepage = "https://fable.io"
packages = [{ include = "fable_library", from = "." }]

[tool.poetry.dependencies]
python = ">= 3.10, < 4.0"

[tool.poetry.dev-dependencies]
pytest = "^8.1"
maturin = "^1.5.0"

[tool.maturin]
python-source = "fable_library"
features = ["pyo3/extension-module"]
module-name = "core._core"

[build-system]
requires = ["poetry-core>=1.0.0", "maturin>=1.5,<2.0"]
build-backend = "maturin"
