name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Separate build job for JS
  build-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300'

    - name: Setup Node.js environment
      uses: actions/setup-node@v3

    - name: Fable Tests
      run: dotnet fsi build.fsx test-js

  # Separate build job for Integration
  build-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300'

    - name: Setup Node.js environment
      uses: actions/setup-node@v3

    - name: Fable Tests
      run: dotnet fsi build.fsx test-integration

  # Separate build job for Python since we use a test matrix (will run in parallell)
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Setup dotnet tools
        run: dotnet tool restore

      # - name: Check F# formatting (fantomas)
      #   run: dotnet fantomas src/Fable.Transforms/Python --check

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Fable Library - Python
        run: dotnet fsi build.fsx library-py

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Fable Tests - Python
        run: dotnet fsi build.fsx test-py

  # Separate build job for Rust (will run in parallell)
  build-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["default", "threaded"]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300'

    - name: Setup Node.js environment
      uses: actions/setup-node@v3

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Fable Tests - Rust
      run: dotnet fsi build.fsx test-rust-${{ matrix.test }}

  build-dart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300'

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1.3

    - name: Fable Tests - Dart
      run: dotnet fsi build.fsx test-dart
